name: Database Connectivity Test

on:
  push:
    branches:
      - main

jobs:
  test_db_connectivity:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11.4

      - name: Install dependencies
        run: |
          python -m pip install mysql-connector-python

      - name: Test Database Connectivity
        run: python -c "import mysql.connector; mysql.connector.connect(host='localhost', user='root', password='Cinema77@drama', database='addresses')"
